/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Vieira Sobral
 */

public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
               
        initComponents();
        String data = horas(0);
        lbl3.setText(data);
        lbl4.setText(System.getProperty("user.name")); 
        setIcon();
    }
    
    
    // MINHAS FUNÇÕES
    
    
    public void salvarArquivo(String x, String nome, String pasta){
		try{
                    new File(pasta).mkdirs();
                    File f = new File(pasta+nome);
                    
                    
                    
                    FileWriter arquivo = new FileWriter(f, true);
                    BufferedWriter grava = new BufferedWriter(arquivo);
                    
                                      
                    grava.write(x+"\r\n");
                    
                    
                    grava.flush();
                    grava.close();
                    
                    System.out.println("Gravação concluida!");
                   
                }catch(IOException e){
			System.out.println("Erro: "+e.toString());
                        e.printStackTrace();
		}
    }
    
    public String horas(int n){
        
        Date hoje = new Date();
        SimpleDateFormat teste;
        teste = new SimpleDateFormat("dd-MM-yyyy");
        if (n==1){
            teste = new SimpleDateFormat("MM");
        }       
        if (n==2){
            teste = new SimpleDateFormat("yyyy");
        }
        String data = teste.format(hoje);
        
        return data;
    }
    
    public String nomeMes(String fim){
        
        switch (fim){
            case "01":
                fim = "Janeiro";
                break;
                
            case "02":
                fim = "Fevereiro";
                break;
            
            case "03":
                fim = "Março";
                break;
                
            case "04":
                fim = "Abril";
                break;

            case "05":
                fim = "Maio";
                break;
                
            case "06":
                fim = "Junho";
                break;
                
            case "07":
                fim = "Julho";
                break;
            
            case "08":
                fim = "Agosto";
                break;
            
            case "09":
                fim = "Setembro";
                break;
            
            case "10":
                fim = "Outubro";
                break;
            
            case "11":
                fim = "Novembro";
                break;
            
            case "12":
                fim = "Dezembro";
                break;
                
        }
        
        return fim;
    }
   
    // FIM MINHAS FUNÇÕES
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONSULTA LOCAL - UFPR PALOTINA");
        setResizable(false);

        lbl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1.setText("NENHUM");

        btn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn2.setText("REGISTRAR");
        btn2.setBorder(null);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn2KeyPressed(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl2.setText("ÚLTIMO CÓDIGO REGISTRADO:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA LOCAL");

        btn1.setText("ABRIR");
        btn1.setBorder(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn1KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        lbl3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("DATA");

        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("USUARIO");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VERSÃO 0.0.4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lbl4)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        
        getRootPane().setDefaultButton(btn2);
        
        String x = txt1.getText();
        String caminho, data, pasta, nMes, nomeMes, ano;
        data = horas(0);
        nMes = horas(1);
        nomeMes = nomeMes(nMes);
        ano = horas(2);
        String usuario = System.getProperty("user.name");
        
        int tamanho = x.length();
        
        lbl1.setForeground(Color.black);
        lbl1.setText(x);
        
        inicio salvar= new inicio();
        
        if(tamanho==8){
            
            pasta = ("C:\\Users\\"+usuario+"\\Documents\\NetBeansProjects\\Projeto2\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); // CAMINHO TESTES
            //pasta = ("C:\\Users\\"+usuario+"\\Google Drive\\A estatística consulta local\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); //CAMINHO PADRÃO
            //pasta = ("C:\\Users\\USUARIO\\Google Drive\\A estatística consulta local\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); //COMPUTADOR2
            caminho = ("Estatística "+data+".txt");
            salvar.salvarArquivo(x, caminho, pasta);
            

        } else {
            lbl1.setForeground(Color.red);
            lbl1.setText("INVÁLIDO!");
        }

        
        
    }//GEN-LAST:event_btn2ActionPerformed
        
    
    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(btn2);
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){  
           btn2.doClick();
           txt1.setText("");

        }
    }//GEN-LAST:event_txt1KeyPressed

    private void btn2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyPressed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(btn2);
    }//GEN-LAST:event_btn2KeyPressed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String caminho, data, pasta, nMes, nomeMes, ano;
        data = horas(0);
        nMes = horas(1);
        nomeMes = nomeMes(nMes);
        ano = horas(2);
        String usuario = System.getProperty("user.name");
        
        pasta = ("C:\\Users\\"+usuario+"\\Documents\\NetBeansProjects\\Projeto2\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); // CAMINHO TESTES
        //pasta = ("C:\\Users\\USUARIO\\Google Drive\\A estatística consulta local\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); // COMPUTADOR2
        //pasta = ("C:\\Users\\"+usuario+"\\Google Drive\\A estatística consulta local\\"+ano+"\\"+nMes+" - "+nomeMes+" "+ano+"\\"); //PADRÃO
        caminho = ("Estatística "+data+".txt");
        
        try {
            java.awt.Desktop.getDesktop().open(new File(pasta+caminho));
        } catch (IOException ex) {
            
			System.out.println("Erro: "+ex.toString());
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "ARQUIVO NÃO EXISTE", "BIBLIOTECA - UFPR", JOptionPane.ERROR_MESSAGE);
                        
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new inicio().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        
        
    }
}
